openapi: 3.0.0
info:
  title: Springboot tutrial APIs - Provider, Service, Citizen
  description: APIs for Services, Providers and Citizens
  contact:
    email: iam.soham@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/iamsoham/springboottutorials/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /providers:
    get:
      summary: lists all providers
      description: list all providers
      operationId: getAllProviders
      responses:
        "200":
          description: all providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
        "400":
          description: bad input parameter
  /provider/{id}:
    get:
      summary: gets a specific provider by id
      description: get by provider id
      operationId: getProviderByID
      parameters: []
      responses:
        "200":
          description: Successfull response with stock info
        "400":
          description: Request is not correct.
        "404":
          description: There is endpoint found.
        "500":
          description: Internal Server Error.
  /provider:
    post:
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: addInventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Provider'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
components:
  schemas:
    Provider:
      required:
      - description
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          example: 20
        name:
          type: string
          example: Loco Poco
        description:
          type: string
          example: Everything for your house
    Manufacturer:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: https://www.acme-corp.com
        phone:
          type: string
          example: 408-867-5309
  responses:
    "201ItemCreated":
      description: Item got created successfully.
    "400BadRequest":
      description: Request is not correct.
    "404NotFound":
      description: There is endpoint found.
    "500InternalServerError":
      description: Internal Server Error.
